//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace TiendaArreglos.Client.Wpf.Model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class TiendaArreglosConfig {
        
        private int lastPrintedNumberField;
        
        private int numberOfTicketsToPrintField;
        
        /// <remarks/>
        public int LastPrintedNumber {
            get {
                return this.lastPrintedNumberField;
            }
            set {
                this.lastPrintedNumberField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfTicketsToPrint {
            get {
                return this.numberOfTicketsToPrintField;
            }
            set {
                this.numberOfTicketsToPrintField = value;
            }
        }
    }
}
